---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    pre_build_image: true
    dns_servers: ['none']
provisioner:
  name: ansible
verifier:
  name: ansible
