---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: management1
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      management1:
        icebergs_system: false
        start_services: true
        enable_services: true
        ep_firewall: true

verifier:
  name: ansible
